### ISSUE TITLE
Simulation failure for client consensus proof carrying messages

### ISSUE THREAD

**Issue by ancazamfir** [cosmos/ibc-go#1732] opened 2022-07-19 16:58 UTC
## Summary of Bug
The following issue was reported on ibc-rs https://github.com/informalsystems/ibc-rs/issues/2433.
It refers to failures for `ConnOpenAck` reported by ibc-go. The failure can also appear in `ConnOpenTry`. They are more obvious when the chain block times are significantly different, I am able to repro easily with 1s and 10s for chains `A` and `B` respectively.
The failures seen are caused by try check:
 https://github.com/cosmos/ibc-go/blob/aaccbd193f19f97f8068278141044bf324e6425c/modules/core/03-connection/keeper/handshake.go#L79  
and the ack check:
https://github.com/cosmos/ibc-go/blob/aaccbd193f19f97f8068278141044bf324e6425c/modules/core/03-connection/keeper/handshake.go#L169 ) in the on-chain handlers. 

They show up while hermes tries to simulate the transaction. It is not clear to me why the check is for `>=` and not `>`. 
It is possible to update the client on chain `A` with a header from `B`, get the consensus proof and submit a `ConnOpenTry` Tx for simulation to chain `B` before `B` advances to a new height.
Would the `>` check be to loose for the `deliverTx`?

## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by AdityaSripal** [comment] 2022-07-20 09:52
Hi Anca, when this bug occurs is it always the case that the heights are in fact equal?

**Comment by ancazamfir** [comment] 2022-07-20 10:32
> Hi Anca, when this bug occurs is it always the case that the heights are in fact equal?

Yes.

**Comment by AdityaSripal** [comment] 2022-07-20 11:19
The purpose of this check is to ensure that the counterparty client's latest height is less than or equal to the highest committed height on our chain.

So if the `ctx.BlockHeight()` is already committed, then we can use `>`. Otherwise, we should use `>=`. Since this is a question regarding how SDK handles the delayed execution model of tendermint, I will double check with the sdk team before proposing a fix.

**Comment by AdityaSripal** [comment] 2022-07-20 13:16
Hi anca, after discussing with the tendermint team it does seem safe to change to `>`.

The height passed in during state machine execution in `DeliverTx` has already been committed. Thus, it is possible for a light client to have already received the update for the latest height before the execution of the handshake message with the latest height as `SelfHeight` runs.

I will make the changes, but since this is touching on security-critical code; I would prefer to wait for @colin-axner to review this issue as well as a sanity check. I would expect the merge next week and releases to follow. Until then, of course a retry will suffice.

Thanks!

**Comment by ancazamfir** [comment] 2022-07-20 14:53
Ok, I am a bit confused, was following the discussion on slack and was also the reason why I was asking if the `>` check was too loose for deliverTx. 

If the handler runs during simulation (height `H`) it should fail on `>` and if it runs during deliverTx (height `H+1`) it should fail on `>=` since there is no way the client on the counterparty could have been updated with `H+1`.
Can the handler know the context the handler runs from? Are you proposing the check is different based on it?

**Comment by AdityaSripal** [comment] 2022-07-20 15:11
Hmm...

This is what I believe is happening.

1. ChainA commits to a height H.
2. ChainB updates its client with Height H as the latest client height.
3. My understanding is that tendermint will then pass the header H to the chainA state machine for execution in height H+1.

If this is indeed the case, then we can use `>`. Because it is possible for a counterparty light client to be updated **before** the height gets processed by the chain's state machine.

**Comment by ancazamfir** [comment] 2022-07-20 16:25
Here is what I think happens in the scenario we see the issue. We reproduce with high block times for `A` (10sec) and small for `B` (1sec).
- app state on `A` is at height `H`
- hermes gets the light client header for latest app state `H` (*) (**)
- updates the client-A on `B` with `H`
- creates a `ConnOpenTry(consensus_height = H)` message for `A` (it also prepends an `UpdateClient` for client-B on `A` but we can skip this)
- simulates `ConnOpenTry` on `A` that fails because of the `>=` check
If we would pass simulation (we do `>` check) the next steps would be:
- hermes sends the Tx with `broadcast_tx_sync`, app runs `checkTx` (for a future `H+1`), Tx is included in mempool
- consensus includes the `ConnOpenTry` Tx in a proposal for block `H+1`, proposal passes then the block and Tx-es are sent to the app for execution
- ibc conn handler runs the `ConnOpenTry` in the app context at `H+1`. Here the `>=` is valid.

(*) This works because the next validator set is retrieved from the [tendermint state store](https://github.com/tendermint/tendermint/blob/2f231ceb952a2426cf3c0abaf0b455aadd11e5b2/rpc/core/consensus.go#L25) so block at `H+1` doesn't need to exist.

(**) We used to use blockchain latest height to get the headers for client update (could be `H+1` vs app's `H`) but we changed that because we saw issues when block execution times were high (e.g. high number of Tx-es in a block). Even simple app queries were failing with `H+1`.
This is not a frequent occurrence on live chains and we were simulating it by introducing sleeps in tendermint block execution.

**Comment by AdityaSripal** [comment] 2022-07-21 15:22
Hmmm... so is there anything that we should be doing in ibc-go for this issue? Or should it be handled on the relayer side?

**Comment by ancazamfir** [comment] 2022-07-21 15:56
> Hmmm... so is there anything that we should be doing in ibc-go for this issue? Or should it be handled on the relayer side?

The only thing i can think of is to have a different check for simulation (`>`) vs deliverTx (`>=`). But not sure it is possible. We can fix it at relayer side by waiting for the chain to advance to next height.

**Comment by smarshall-spitzbart** [comment] 2022-08-04 19:44
Hey all, this was posted in an informal slack channel but thought I'd post here as well, since my issue may be related to this thread.

I'm [expanding some integration tests for ICS](https://github.com/cosmos/interchain-security/compare/send-tokens-test-addition...undelegate-test-addition) and running into an issue with hermes and/or the IBC implementation. It seems that the clock for the relayer process is out of sync with one of the chains within our tests, which is odd since both processes live within the same docker container.

Error output: 
```
invalid light block: header from the future: header_time=2022-08-04T18:45:41.140553261Z now=2022-08-04T18:45:30.680924006Z
```

Any config values I can change to prevent this? Thank you

**Comment by smarshall-spitzbart** [comment] 2022-08-05 18:01
Since my issue is specific to clock timing, and not block height, I've created a [separate issue ](https://github.com/informalsystems/ibc-rs/issues/2536). Feel free to consolidate the two issue if you think they're related tho

**Comment by colin-axner** [comment] 2022-08-09 16:20
Excellent debugging @ancazamfir. I believe you are correct

It looks like the block height is incremented on [BeginBlock](https://github.com/cosmos/cosmos-sdk/blob/main/baseapp/abci.go#L167) which makes sense why this would pass in simulation. Essentially the tx is being simulated after `Commit()`, but before `BeginBlock()`, thus it is simulating on the last committed block

I asked to increase the strictness of this [check](https://github.com/cosmos/cosmos-sdk/issues/6354), but I realize now because of delayed block execution, I think it can be weakened? The historical info is set on [BeginBlock](https://github.com/cosmos/cosmos-sdk/blob/main/x/staking/abci.go#L19), indicating that the app hash is actually the app hash calculated by the last signed header. It still is logically kind of odd since given delayed execution, the only time it should be possible to submit a conn open try with the same height is on simulation

I think I'd prefer to leave the code as is assuming it doesn't cause too much disruption to the relayers

**Comment by crodriguezvega** [comment] 2022-08-19 14:02
I confirmed with @adizere that the hermes relayer is going to handle this situation, therefore I am closing the issue for now.

**Closed by crodriguezvega** 2022-08-19 14:02 UTC
