### ISSUE TITLE
Update `AssertTxFailure` to check codespace and ABCI code when not a compatibility test

### ISSUE THREAD

**Issue by chatton** [cosmos/ibc-go#3653] opened 2023-05-25 09:35 UTC
## Summary of Bug

See [this comment](https://github.com/cosmos/ibc-go/pull/3512/files/f92d25338866acd0abdf4800e18b015c67d133a4#r1205243240)

I think it should be a safe assumption to say that if ChainA Tag != ChainB Tag we should not check for ABCI code and Error.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by damiannolan** [comment] 2023-05-25 12:34
duplicate of #3652?

**Closed** 2023-06-01 15:42 UTC
Labels: e2e
