### ISSUE TITLE
Protos flow

### ISSUE THREAD

**Issue by faddat** [cosmos/ibc-go#1798] opened 2022-07-27 14:45 UTC
## Summary of Bug

```bash
make proto-update-deps
make proto-all
```

Doesn't work quite right. 

* https://github.com/cosmos/ibc-go/pull/1653

Has a change to makefile that fetches the correct ics23 .proto file, but we should work on the flow till it is buttery smooth. 

Vuong uses arch, that works. 

I use a mac, it doesn't.

The ubuntu .gitpod.yml container that comes by default, also doesn't.  ghcr.io/notional-labs/cosmos does work. 

## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by nicopernas** [comment] 2022-07-28 12:52
I can repro the issue you are having on macOS caused by the `sed` command in the Makefile. This here should fix it and should work for both macOS and GNU sed

```diff
diff --git a/Makefile b/Makefile
index c8a42e0e..656cfd6a 100644
--- a/Makefile
+++ b/Makefile
@@ -462,7 +462,7 @@ proto-update-deps:

 ## insert go package option into proofs.proto file
 ## Issue link: https://github.com/confio/ics23/issues/32
-       @sed -i '4ioption go_package = "github.com/confio/ics23/go";' $(CONFIO_TYPES)/proofs.proto
+       @sed -ri -e 's|^(package ics23;)$$|\1\noption go_package = "github.com/confio/ics23/go";|' $(CONFIO_TYPES)/proofs.proto
```

With that, `make proto-update-deps` starts working. However, the `proto-lint` target fails because confio's proof.proto has issues.

**Comment by crodriguezvega** [comment] 2022-08-07 12:32
I run both

```
make proto-update-deps
make proto-all
```

on my mac on `main` and they work just fine, so I think I will close the issue for now. If the problem re-appears we can open a new issue.

Thanks very much to both of you!

**Closed by crodriguezvega** 2022-08-07 12:32 UTC
