### ISSUE TITLE
client state is not active

### ISSUE THREAD

**Issue by tomas-dora** [cosmos/ibc-go#4795] opened 2023-09-30 08:06 UTC
I was able to make ibc transfers through this channel before and the status of hermes has always been normal, I don't know why suddenly I can't transfer money today.

What is the reason for this error? Under what circumstances will the client of ibc become `inactive`? How can I avoid this?

```
Error: rpc error: code = Unknown desc = rpc error: code = Unknown desc = failed to execute message; message index: 0: cannot send packet using client (07-tendermint-2) with status Expired: client state is not active [cosmos/ibc-go/v7@v7.1.0/modules/core/04-channel/keeper/packet.go:75] With gas wanted: '18446744073709551615' and gas used: '59922' : unknown request
```

**Comment by tomas-dora** [comment] 2023-09-30 09:47
this is my hermes log:
```
2023-09-30T09:45:08.142369Z  INFO ThreadId(01) # Chain: doravota-devnet
  - Client: 07-tendermint-2
    * Connection: connection-3
      | State: OPEN
      | Counterparty state: OPEN
      + Channel: channel-1
        | Port: transfer
        | State: OPEN
        | Counterparty: channel-1260
# Chain: osmo-test-5
  - Client: 07-tendermint-681
    * Connection: connection-611
      | State: OPEN
      | Counterparty state: OPEN
      + Channel: channel-1260
        | Port: transfer
        | State: OPEN
        | Counterparty: channel-1

2023-09-30T09:45:08.142480Z  INFO ThreadId(01) spawn:chain{chain=doravota-devnet}:client{client=07-tendermint-2}:connection{connection=connection-3}: connection is OPEN, state on destination chain is OPEN chain=doravota-devnet connection=connection-3 counterparty_chain=osmo-test-5
2023-09-30T09:45:08.142541Z  INFO ThreadId(01) spawn:chain{chain=doravota-devnet}:client{client=07-tendermint-2}:connection{connection=connection-3}: connection is already open, not spawning Connection worker chain=doravota-devnet connection=connection-3
2023-09-30T09:45:08.142596Z  INFO ThreadId(01) spawn:chain{chain=doravota-devnet}:client{client=07-tendermint-2}:connection{connection=connection-3}: no connection workers were spawn chain=doravota-devnet connection=connection-3
2023-09-30T09:45:08.142632Z  INFO ThreadId(01) spawn:chain{chain=doravota-devnet}:client{client=07-tendermint-2}:connection{connection=connection-3}:channel{channel=channel-1}: channel is OPEN, state on destination chain is OPEN chain=doravota-devnet counterparty_chain=osmo-test-5 channel=channel-1
2023-09-30T09:45:08.145887Z ERROR ThreadId(01) spawn:chain{chain=doravota-devnet}:client{client=07-tendermint-2}:connection{connection=connection-3}:channel{channel=channel-1}:foreign_client.validated_client_state{client=osmo-test-5->doravota-devnet:07-tendermint-2}: client state is not valid: latest height is outside of trusting period! latest_height=5-2200470 network_timestmap=2023-09-29T05:27:22.534401074Z consensus_state_timestamp=2023-08-16T17:55:35.934330642Z elapsed=3756706.600070432s
2023-09-30T09:45:08.145947Z  WARN ThreadId(01) spawn:chain{chain=doravota-devnet}:client{client=07-tendermint-2}:connection{connection=connection-3}:channel{channel=channel-1}: skipping refresh client task on frozen client client=07-tendermint-2
2023-09-30T09:45:08.148631Z ERROR ThreadId(01) spawn:chain{chain=doravota-devnet}:client{client=07-tendermint-2}:connection{connection=connection-3}:channel{channel=channel-1}:foreign_client.validated_client_state{client=osmo-test-5->doravota-devnet:07-tendermint-2}: client state is not valid: latest height is outside of trusting period! latest_height=5-2200470 network_timestmap=2023-09-29T05:27:22.534401074Z consensus_state_timestamp=2023-08-16T17:55:35.934330642Z elapsed=3756706.600070432s
2023-09-30T09:45:08.148683Z  WARN ThreadId(01) spawn:chain{chain=doravota-devnet}:client{client=07-tendermint-2}:connection{connection=connection-3}:channel{channel=channel-1}: skipping detect misbehavior task on frozen client client=07-tendermint-2 src_chain=osmo-test-5 dst_chain=doravota-devnet
2023-09-30T09:45:08.148717Z  INFO ThreadId(01) spawn:chain{chain=doravota-devnet}:client{client=07-tendermint-2}:connection{connection=connection-3}:channel{channel=channel-1}: spawned client worker: client::osmo-test-5->doravota-devnet:07-tendermint-2
2023-09-30T09:45:08.171626Z  INFO ThreadId(01) spawn:chain{chain=doravota-devnet}:client{client=07-tendermint-2}:connection{connection=connection-3}: done spawning channel workers chain=doravota-devnet channel=channel-1
2023-09-30T09:45:08.171959Z  INFO ThreadId(01) spawn:chain{chain=doravota-devnet}: spawning Wallet worker: wallet::doravota-devnet
2023-09-30T09:45:08.172018Z  INFO ThreadId(01) spawn:chain{chain=osmo-test-5}:client{client=07-tendermint-681}:connection{connection=connection-611}: connection is OPEN, state on destination chain is OPEN chain=osmo-test-5 connection=connection-611 counterparty_chain=doravota-devnet
2023-09-30T09:45:08.172056Z  INFO ThreadId(01) spawn:chain{chain=osmo-test-5}:client{client=07-tendermint-681}:connection{connection=connection-611}: connection is already open, not spawning Connection worker chain=osmo-test-5 connection=connection-611
2023-09-30T09:45:08.172081Z  INFO ThreadId(01) spawn:chain{chain=osmo-test-5}:client{client=07-tendermint-681}:connection{connection=connection-611}: no connection workers were spawn chain=osmo-test-5 connection=connection-611
2023-09-30T09:45:08.172110Z  INFO ThreadId(01) spawn:chain{chain=osmo-test-5}:client{client=07-tendermint-681}:connection{connection=connection-611}:channel{channel=channel-1260}: channel is OPEN, state on destination chain is OPEN chain=osmo-test-5 counterparty_chain=doravota-devnet channel=channel-1260
2023-09-30T09:45:08.177079Z ERROR ThreadId(01) spawn:chain{chain=osmo-test-5}:client{client=07-tendermint-681}:connection{connection=connection-611}:channel{channel=channel-1260}:foreign_client.validated_client_state{client=doravota-devnet->osmo-test-5:07-tendermint-681}: client state is not valid: latest height is outside of trusting period! latest_height=0-656218 network_timestmap=2023-09-30T09:45:00.687241902Z consensus_state_timestamp=2023-08-12T11:13:52.04760108Z elapsed=4228268.639640822s
2023-09-30T09:45:08.177131Z  WARN ThreadId(01) spawn:chain{chain=osmo-test-5}:client{client=07-tendermint-681}:connection{connection=connection-611}:channel{channel=channel-1260}: skipping refresh client task on frozen client client=07-tendermint-681
2023-09-30T09:45:08.179497Z ERROR ThreadId(01) spawn:chain{chain=osmo-test-5}:client{client=07-tendermint-681}:connection{connection=connection-611}:channel{channel=channel-1260}:foreign_client.validated_client_state{client=doravota-devnet->osmo-test-5:07-tendermint-681}: client state is not valid: latest height is outside of trusting period! latest_height=0-656218 network_timestmap=2023-09-30T09:45:00.687241902Z consensus_state_timestamp=2023-08-12T11:13:52.04760108Z elapsed=4228268.639640822s
2023-09-30T09:45:08.179547Z  WARN ThreadId(01) spawn:chain{chain=osmo-test-5}:client{client=07-tendermint-681}:connection{connection=connection-611}:channel{channel=channel-1260}: skipping detect misbehavior task on frozen client client=07-tendermint-681 src_chain=doravota-devnet dst_chain=osmo-test-5
2023-09-30T09:45:08.179587Z  INFO ThreadId(01) spawn:chain{chain=osmo-test-5}:client{client=07-tendermint-681}:connection{connection=connection-611}:channel{channel=channel-1260}: spawned client worker: client::doravota-devnet->osmo-test-5:07-tendermint-681
2023-09-30T09:45:08.193727Z  INFO ThreadId(01) spawn:chain{chain=osmo-test-5}:client{client=07-tendermint-681}:connection{connection=connection-611}: done spawning channel workers chain=osmo-test-5 channel=channel-1260
```

**Comment by crodriguezvega** [comment] 2023-10-02 07:19
Hi @tomas-dora. The problem is in these error messages that say:

```
client state is not valid: latest height is outside of trusting period! 
latest_height=5-2200470 
network_timestmap=2023-09-29T05:27:22.534401074Z 
consensus_state_timestamp=2023-08-16T17:55:35.934330642Z 
elapsed=3756706.600070432s
```

This means that the light client has expired because it hasn't been updated (i.e. the client has not been updated with new consensus information) for a period of time longer than the trusting period.

From the error messages, it looks like these 2 light clients were updated last on August 16th and August 12th, respectively. Assuming a 2-week trusting period, these dates are earlier than 2 weeks then.

In order to recover these 2 light clients you need to follow the process outlined [here](https://ibc.cosmos.network/main/ibc/proposals).

Since there is no action to take from our side, I will close the issue. Feel free still to comment on it if you have any more questions.

**Closed by crodriguezvega** 2023-10-02 07:19 UTC
