### ISSUE TITLE
Missing pagination for some bulk queries

### ISSUE THREAD

**Issue by ancazamfir** [cosmos/ibc-go#118] opened 2021-04-14 10:07 UTC
## Summary
While looking at some pagination issues in `hermes` queries (https://github.com/informalsystems/ibc-rs/issues/811)  found that there is no `pagination` field for the following queries:
`QueryClientConnectionsRequest`, `QueryUnreceivedPacketsRequest` , `QueryUnreceivedAcksRequest`.

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by ancazamfir** [comment] 2021-04-14 10:47
Actually probably not required for `QueryUnreceivedPacketsRequest`  and `QueryUnreceivedAcksRequest` as we query for specific sequences.

**Comment by crodriguezvega** [comment] 2022-12-02 12:26
@ancazamfir the lack of pagination in `QueryClientConnectionsRequest`, is still an issue for hermes?

I ask because I was looking a bit into it and I think that it will not be so straightforward to add pagination to it. I will try to explain...

I think the regular way of adding pagination to the [gRPC endpoint](https://github.com/cosmos/ibc-go/blob/main/modules/core/03-connection/keeper/grpc_query.go#L83) using SDK's machinery would be something like this:

```go
clientConnectionPaths := []string{}
store := prefix.NewStore(ctx.KVStore(q.storeKey), []byte(host.ClientConnectionsKey(req.ClientId)))
pageRes, err := query.Paginate(store, req.Pagination, func(key, value []byte) error {
	var result types.ClientPaths
	if err := q.cdc.Unmarshal(value, &result); err != nil {
		return err
	}

	clientConnectionPaths = append(clientConnectionPaths, result.Paths...)
	return nil
})
if err != nil {
	return nil, err
}
```

The problem is that the connection paths for a given client ID are all stored as a `[]string` in the key `clients/<client-id>/connections`, so when doing the `query.Paginate` there's always just one page returned that contains all the connection paths for that client, since there's nothing to paginate over on the provided prefix (`[]byte(host.ClientConnectionsKey(req.ClientId))`).

Alternatively we could get all the connection paths [as it is done right now](https://github.com/cosmos/ibc-go/blob/main/modules/core/03-connection/keeper/grpc_query.go#L93) and do the pagination ourselves, but before building something so specific for this query, I would like to know if there's really a strong need for pagination in this query.

cc @colin-axner to double check my reasoning here when he has some time or provide alternatives ideas.

**Comment by ancazamfir** [comment] 2022-12-09 02:04
It's been a long time and can't recall the details. I was doing local testing with high scale numbers but can't recall if anything was breaking and how it was breaking. We can probably do more tests. 
Are you asking in order to close the issue?

**Comment by crodriguezvega** [comment] 2022-12-09 11:39
> Are you asking in order to close the issue?

Yes, that's basically the reason. I can understand this could be a problem in stress-testing scenarios if you add lots of connections on top of the client, but if this is not an issue that would likely be hit in real scenarios, then I would consider closing the issue. It can be open anyway again if needed!

**Comment by crodriguezvega** [comment] 2023-01-11 21:21
Closing for now since there's no action to take at the moment. We will reopen if needed.

**Closed by crodriguezvega** 2023-01-11 21:21 UTC
Labels: client-UX, nice-to-have
