### ISSUE TITLE
Missing checks in gRPC queries

### ISSUE THREAD

**Issue by ancazamfir** [cosmos/ibc-go#4140] opened 2023-07-20 14:02 UTC
## Summary of Bug
Some gRPC queries are missing validation.

## Expected Behaviour
Packet level query with nonexistent channel should return error instead of empty output.

## Version
v7.2.0, also checked the code in main

## Steps to Reproduce
Here is an example
```
$ grpcurl --plaintext -d '{"port_id":"transfer", "channel_id":"channel-43"}' stride-grpc.polkachu.com:12290 ibc.core.channel.v1.Query.PacketCommitments
{
  "pagination": {

  },
  "height": {
    "revisionNumber": "1",
    "revisionHeight": "4626258"
  }
}
$ grpcurl --plaintext -d '{"port_id":"icacontroller-osmosis-1.FEE", "channel_id":"channel-43"}' stride-grpc.polkachu.com:12290 ibc.core.channel.v1.Query.PacketCommitments
{
  "pagination": {

  },
  "height": {
    "revisionNumber": "1",
    "revisionHeight": "4626258"
  }
}
```
This is the nonexistent channel:
```
$ grpcurl --plaintext -d '{"port_id":"transfer", "channel_id":"channel-43"}' stride-grpc.polkachu.com:12290 ibc.core.channel.v1.Query.Channel
ERROR:
  Code: NotFound
  Message: port-id: transfer, channel-id channel-43: channel not found
```

The existing one:
```
$ grpcurl --plaintext -d '{"port_id":"icacontroller-osmosis-1.FEE", "channel_id":"channel-43"}' stride-grpc.polkachu.com:12290 ibc.core.channel.v1.Query.Channel
{
  "channel": {
    "state": "STATE_OPEN",
...
```
There are other queries that are missing the channel check (PacketReceipt, PacketCommitment, PacketAcknowledgement...), didn't check them all.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment] 2023-07-21 09:15
Thanks for raising this issue, @ancazamfir. I tried to be as exhaustive as possible, and I see that the issue is present in the following gRPC handlers.

In 29-fee:
- [`IncentivizedPacketsForChannel`l](https://github.com/cosmos/ibc-go/blob/31b3c6000ca05be316d5bb49d34e073ed07a82e8/modules/apps/29-fee/keeper/grpc_query.go#L71)
- [`FeeEnabledChannel`](https://github.com/cosmos/ibc-go/blob/31b3c6000ca05be316d5bb49d34e073ed07a82e8/modules/apps/29-fee/keeper/grpc_query.go#L219)

In transfer:
- [`EscrowAddress`](https://github.com/cosmos/ibc-go/blob/31b3c6000ca05be316d5bb49d34e073ed07a82e8/modules/apps/transfer/keeper/grpc_query.go#L115)

In 04-channel:
- [`Channel`](https://github.com/cosmos/ibc-go/blob/31b3c6000ca05be316d5bb49d34e073ed07a82e8/modules/core/04-channel/keeper/grpc_query.go#L26)
- [`ChannelClientState`](https://github.com/cosmos/ibc-go/blob/31b3c6000ca05be316d5bb49d34e073ed07a82e8/modules/core/04-channel/keeper/grpc_query.go#L136)
- [`PacketCommitment`](https://github.com/cosmos/ibc-go/blob/31b3c6000ca05be316d5bb49d34e073ed07a82e8/modules/core/04-channel/keeper/grpc_query.go#L205)
- [`PacketCommitments`](https://github.com/cosmos/ibc-go/blob/31b3c6000ca05be316d5bb49d34e073ed07a82e8/modules/core/04-channel/keeper/grpc_query.go#L230)
- [`PacketReceipt`](https://github.com/cosmos/ibc-go/blob/31b3c6000ca05be316d5bb49d34e073ed07a82e8/modules/core/04-channel/keeper/grpc_query.go#L269)
- [`PacketAcknowledgement`](https://github.com/cosmos/ibc-go/blob/31b3c6000ca05be316d5bb49d34e073ed07a82e8/modules/core/04-channel/keeper/grpc_query.go#L291)
- [`PacketAcknowledgements`](https://github.com/cosmos/ibc-go/blob/31b3c6000ca05be316d5bb49d34e073ed07a82e8/modules/core/04-channel/keeper/grpc_query.go#L316)
- [`UnreceivedAcks`](https://github.com/cosmos/ibc-go/blob/31b3c6000ca05be316d5bb49d34e073ed07a82e8/modules/core/04-channel/keeper/grpc_query.go#L478)

For all the handlers above we should have checks like [these](https://github.com/cosmos/ibc-go/blob/31b3c6000ca05be316d5bb49d34e073ed07a82e8/modules/core/04-channel/keeper/grpc_query.go#L517-L528), so that we both check that the port ID and channel ID are valid identifiers and the channel exists. Some of the handlers have already the former check, but not the latter. 

Whoever would like to work on this, please also add tests and open multiple PRs (maybe opening a single PR for each endpoint is too much, but one way option could be to open one PR for each module - 1 for fee, 1 for transfer, 1 for 04-channel).

**Comment by chatton** [comment] 2024-03-25 15:14
assigned it to you @bznein :+1:

**Closed** 2024-04-03 18:25 UTC
Labels: bug, help wanted, gRPC
