### ISSUE TITLE
Interchain accounts packet timeout fails next sequence recv verification

### ISSUE THREAD

**Issue by damiannolan** [cosmos/ibc-go#1021] opened 2022-02-28 10:50 UTC
## Summary of Bug

The following is a summary of an issue encountered when testing an interchain-accounts timeout scenario.
**Scenario:** Register an interchain account using controller chain A on host chain B. Kill the relayer process. Send an interchain accounts packet from chainA -> chainB. Wait for 1 min timeout period. Restart the relayer process. 
**Expected behaviour:** The packet should timeout gracefully and the ordered channel should be closed. The channel is expected to be able to be reopened and operational.

Upon packet timeout the relayer attempts to send a `MsgTimeout` to the sender chain A and fails proof verification on [04-channel/keeper/timeout.go#L110 - `VerifyNextSequenceRecv()`](https://github.com/cosmos/ibc-go/blob/v3.0.0-rc0/modules/core/04-channel/keeper/timeout.go#L110)

Both channel ends remain in an `OPEN` state and the channel becomes unusable as further packets sent do not contain the expected sequence. 

## Version

interchain-accounts demo repo [30113be](https://github.com/cosmos/interchain-accounts/commit/30113bed9a12197f14d50fdfee8220e148953ee3)
ibc-go `v3.0.0-rc0`
hermes `v0.12.0`

## Steps to Reproduce

1. Checkout the following interchain-accounts demo branch: [interchain-accounts/pulls/86](https://github.com/cosmos/interchain-accounts/pull/86)

2. Following the demo scenario as documented on the interchain-accounts [README.md](https://github.com/cosmos/interchain-accounts#readme).

- Initialise two test chains (chain A and chain B) where chain A assumes the role of ICA controller and chain B assumes the role of ICA host.
```
# bootstrap and start the two test chains
make init

# start the hermes relayer v0.12.0
make start-rly

# store the demo wallet addresses in the current env
export DEMOWALLET_1=$(icad keys show demowallet1 -a --keyring-backend test --home ./data/test-1) && echo $DEMOWALLET_1;
export DEMOWALLET_2=$(icad keys show demowallet2 -a --keyring-backend test --home ./data/test-2) && echo $DEMOWALLET_2;

# register an interchain account on host chain B from controller chain A
icad tx intertx register --from $DEMOWALLET_1 --connection-id connection-0 --chain-id test-1 --home ./data/test-1 --node tcp://localhost:16657 --keyring-backend test -y

# when handshake is successful, send some funds to the interchain account
icad tx bank send $DEMOWALLET_2 $ICA_ADDR 10000stake --chain-id test-2 --home ./data/test-2 --node tcp://localhost:26657 --keyring-backend test -y
```

- Stop the relayer, submit a new interchain-accounts tx and wait approx. 1 min for the timeout to elapse.
```
icad tx intertx submit \
'{
    "@type":"/cosmos.staking.v1beta1.MsgDelegate",
    "delegator_address":"cosmos15ccshhmp0gsx29qpqq6g4zmltnnvgmyu9ueuadh9y2nc5zj0szls5gtddz",
    "validator_address":"cosmosvaloper1qnk2n4nlkpw9xfqntladh74w6ujtulwnmxnh3k",
    "amount": {
        "denom": "stake",
        "amount": "1000"
    }
}' --connection-id connection-0 --from $DEMOWALLET_1 --chain-id test-1 --home ./data/test-1 --node tcp://localhost:16657 --keyring-backend test -y
```

- Restart the relayer and observe the retry loop by hermes with the following error:
```
2022-02-28T10:39:58.514253Z ERROR ThreadId(20) send_tx_check{id=OYUT2Twsoz}:send_tx{id=test-1}:estimate_gas: 
failed to simulate tx. propagating error to caller: 
gRPC call failed with status: status: Unknown, message: "failed to execute message; message index: 1: 
timeout packet verification failed: failed next sequence receive verification for client (07-tendermint-0): 
chained membership proof contains nonexistence proof at index 0. 
If this is unexpected, please ensure that proof was queried from a height that contained the value in store
and was queried with the correct key. 
The key used: /ibc/nextSequenceRecv%2Fports%2Ficahost%2Fchannels%2Fchannel-0: invalid proof", 
details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "x-cosmos-block-height": "501"} }
```

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by AdityaSripal** [comment] 2022-02-28 10:59
> "failed to execute message; message index: 1: 
timeout packet verification failed: failed next sequence receive verification for client (07-tendermint-0): 
chained membership proof contains nonexistence proof at index 0. 

This means that there does not exist a value for the key that you queried. Are you 100% sure that the portID and channelID are correct?

If you're timing out because a message was not executed in time, then shouldn't we be querying the controller side and submitting to the host side? So it looks to me like the query:

`ibc/nextSequenceRecv%2Fports%2Ficahost%2Fchannels%2Fchannel-0`

is wrong.

We need to be querying with port `icacontroller`. I would double check that we are actually querying the right chain (controller chain), and if we are then we should be querying with portID: `icacontroller` and the channelID on the controller side

**Comment by damiannolan** [comment] 2022-02-28 12:45
The `MsgTimeout` should be submitted to the source chain (chain A - controller), with a proof and nextSequenceRecv queried from the destination chain (chain B - host), correct? 

From what I could dig through the hermes source the query seems to be initiated here: https://github.com/informalsystems/ibc-rs/blob/v0.12.0/relayer/src/link/relay_path.rs#L1102

**Comment by ancazamfir** [comment] 2022-02-28 15:12
the problem is that hermes (still) doesn't set properly the relay path ordering (so we send the non-existence proofs as if it's an unordered channel). I thought we fixed this. Could you try `anca/ordered_fixes` branch of hermes?

**Comment by damiannolan** [comment] 2022-02-28 15:55
Tested using `anca/ordered_fixes` branch and appears to work like a charm. Will run some more manual QA on this, but looks good. Thanks so much again @ancazamfir! 

Shall I leave this issue open until the hermes fix is delivered in a patch release? Otherwise I am happy to close it. cc. @crodriguezvega @AdityaSripal

**Comment by adizere** [comment] 2022-02-28 16:41
As a final check, can we please also test with https://github.com/informalsystems/ibc-rs/pull/1887 ? This PR is a superset of Anca's patch, so I'd expect it to work, but it also includes modifications for a corner-case with packet clearing on ordered channels that should be take into account. Thank you in advance Damian for any feedback/review of 1887!

**Comment by crodriguezvega** [comment] 2022-03-01 08:41
I think we can close the issue, since there are no changes needed in ibc-go for now. 

Thanks everyone for the quick response!

**Closed by crodriguezvega** 2022-03-01 08:41 UTC
Labels: bug, needs discussion, 27-interchain-accounts
