### ISSUE TITLE
Remove deprecated Coordinator functions

### ISSUE THREAD

**Issue by DimitrisJim** [cosmos/ibc-go#5720] opened 2024-01-25 09:14 UTC
Follow up to https://github.com/cosmos/ibc-go/issues/3999, remove the functions marked as deprecated in that issue. These can be removed in v10.

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by fluz** [comment] 2024-01-25 11:17
Hi @DimitrisJim, 

May I take this one?

**Comment by crodriguezvega** [comment] 2024-01-25 11:47
Thanks, @fluz, but I think we should hold on this one for now, because if we remove them now, they will be removed in v9 and we want to remove them in the following major release.

**Comment by crodriguezvega** [comment] 2024-01-25 11:49
@DimitrisJim This is actually a duplicate of https://github.com/cosmos/ibc-go/issues/5063, are you ok if we close it?

**Closed as completed** 2024-01-25 11:50 UTC
Labels: good first issue, testing, icebox, deprecated
