### ISSUE TITLE
cannot unmarshal ICS-27 interchain accounts metadata: unknown data type

### ISSUE THREAD

**Issue by jununifi** [cosmos/ibc-go#2696] opened 2022-11-07 12:43 UTC
## Summary of Bug

I am trying to connect two chains with interchain account. And getting following issue while creating a channel using hermes.
```
ERROR ThreadId(30) send_tx_with_account_sequence_retry{id=ununifi-test-private-m1}:estimate_gas: failed to simulate tx. propagating error to caller: gRPC call failed with status: status: Unknown, message: "failed to execute message; message index: 0: channel open init callback failed: cannot unmarshal ICS-27 interchain accounts metadata: unknown data type", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "x-cosmos-block-height": "70"} }
```

Two are same binary with different home directory.
I have looked into it on previous issues ticket and even tried adding logs to debug but couldn't find the cause of the issue.

Would this be the version mismatch between hermes and ibc-go? If so, is there version compatibility map between hermes and ibc-go version?

## Expected Behaviour

Channel creates successfully.

## Version

```
hermes version: hermes 1.0.0+ed4dd8c
IBC go version: github.com/cosmos/ibc-go/v3@v3.0.0
```

## Steps to Reproduce

```
sh start-chain1.sh
sh start-chain2.sh
sh start-hermes.sh

hermes create channel --order ordered --a-chain ununifi-test-private-m1 --a-connection $CONNECTION --a-port icacontroller-chain2 --b-port icahost --yes;
```

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment] 2022-11-07 21:24
Hi @jununifi. So you get this error because the `version` string for the channel fails to unmarshal as [`Metadata` type](https://github.com/cosmos/ibc-go/blob/release/v3.0.x/modules/apps/27-interchain-accounts/types/metadata.pb.go#L26-L42) in [the `OnChannelOpenInit` callback on the controller submodule](https://github.com/cosmos/ibc-go/blob/release/v3.0.x/modules/apps/27-interchain-accounts/controller/keeper/handshake.go#L44-L47). For the channel to be opened you would need to use the `--channel-version` argument of hermes and pass in a JSON-encoded string of the `Metadata` struct. 

However, even if you managed to successfully open the channel I think you're trying to use ICA in a way that it's not meant. Even if you open the channel you will not be able to send messages to the host chain because there's no entry point for submitting messages in ibc-go v3.0.0. In order to do that you need an [authentication module](https://ibc.cosmos.network/v3.0.0/apps/interchain-accounts/auth-modules.html) like [this one](https://github.com/cosmos/gaia/tree/main/x/icamauth). This authentication module has a message server that can be used to [register interchain accounts](https://github.com/cosmos/gaia/blob/main/x/icamauth/keeper/msg_server.go#L27) and [send messages to the host](https://github.com/cosmos/gaia/blob/main/x/icamauth/keeper/msg_server.go#L38).

In v6.0.0 we are introducing a similar message server, so that no separate authentication module is needed. So if you can, we recommend that you try using that version instead (the latest pre-release it's [v6.0.0-beta1](https://github.com/cosmos/ibc-go/releases/tag/v6.0.0-beta1)).

I will close the issue for now, since this is not a bug in ibc-go. Feel free to comment on it still if you have any other questions.

**Closed by crodriguezvega** 2022-11-07 21:24 UTC

**Comment by jununifi** [comment] 2022-11-10 02:01
Thanks for your response @crodriguezvega 
My concern is that both chain is running same codebase, and I have checked Metadata object and it was exactly same.
For auth module integration, it can be done, current issue is blocker on channel creation.
Can you share example JSON for `--channel-version` or any other document related to it?

**Comment by MalteHerrmann** [comment] 2023-01-14 00:08
@crodriguezvega I'm facing this exact problem - running two chains connected via Hermes. One is Evmos, which uses the stock ICA host functionality, and the [Interchain Accounts Demo chain](https://github.com/cosmos/interchain-accounts-demo), which is provided by Cosmos itself.

This error occurs when executing `icad tx intertx register --from "$WALLET_1" --connection-id connection-0 -b block -y`.

```
2023-01-14T00:03:27.131274Z ERROR ThreadId(22) worker.batch{chain=icademo_localnet-4}:supervisor.handle_batch{chain=icademo_localnet-4}:supervisor.process_batch{chain=icademo_localnet-4}:worker.channel{channel=channel::channel-0/icacontroller-cosmos14zs2x38lmkw4eqvl3lpml5l8crzaxn6m7wuznx:icademo_localnet-4->evmoslocalnet_9001-1}:send_messages_and_wait_commit{chain=evmoslocalnet_9001-1 tracking_id=ChannelOpenTry}:send_tx_with_account_sequence_retry{chain=evmoslocalnet_9001-1 account.sequence=5}:estimate_gas: failed to simulate tx. propagating error to caller: gRPC call failed with status: status: Unknown, message: "failed to execute message; message index: 1: channel open try callback failed: cannot unmarshal ICS-27 interchain accounts metadata: unknown data type [cosmos/ibc-go/v5@v5.2.0/modules/apps/27-interchain-accounts/host/keeper/handshake.go:39] With gas wanted: '18446744073709551615' and gas used: '195245' ", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "x-cosmos-block-height": "29"} }
```

During the setup of Hermes I see these logs, which would make me assume that the connection is setup correctly:

```
...

2023-01-14T00:01:58.943572Z  INFO ThreadId(01) 
# Chain: evmoslocalnet_9001-1
  - Client: 07-tendermint-0
    * Connection: connection-0
      | State: OPEN
      | Counterparty state: OPEN
# Chain: icademo_localnet-4
  - Client: 07-tendermint-0
    * Connection: connection-0
      | State: OPEN
      | Counterparty state: OPEN

2023-01-14T00:01:58.944760Z  INFO ThreadId(01) spawn:chain{chain=evmoslocalnet_9001-1}:client{client=07-tendermint-0}:connection{connection=connection-0}: connection is OPEN, state on destination chain is OPEN chain=evmoslocalnet_9001-1 connection=connection-0 counterparty_chain=icademo_localnet-4

...
```

I have tried with versions of the connected chains on both IBC-Go v5 and v6 but getting the same error everytime. Would appreciate some insight or pointers, where to continue my research. Thanks!
