### ISSUE TITLE
Allow for unregistered cli commands for host and controller submodules that will not be used

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#2320] opened 2022-09-20 16:57 UTC
## Summary

Opening for food for thought. I consider this low priority. If a controller or host keeper is nil in app.go, the cli commands ideally shouldn't be added to the command in these cases. Optionally we could return a nice error message if a user tries to use these commands

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment] 2023-02-13 20:40
Closing this as duplicate of https://github.com/cosmos/ibc-go/issues/2978.

**Closed by crodriguezvega** 2023-02-13 20:40 UTC
