### ISSUE TITLE
docs: issue with mobile version for 'next'

### ISSUE THREAD

**Issue by womensrights** [cosmos/ibc-go#6500] opened 2024-06-05 11:55 UTC
Users visiting the docs homepage for version [“next”](https://ibc.cosmos.network/main)  **on mobile** experience a JS error called “unexpected token”. Users bounce off the site after this error, this problem will be reduced if the default is to use the latest supported version of docs ([#6499](https://github.com/cosmos/ibc-go/issues/6499)) but it should still be possible to view next on mobile.

**Comment by srdtrk** [comment] 2024-06-11 10:40
I can't seem to reproduce this issue?

**Comment by srdtrk** [comment] 2024-06-11 11:06
I noticed that base docusaurus allows changing version from the sidebar in homepage. But I've removed the sidebar, so the only way to change versions is to change the URL at the moment or click the banner. I guess I can fix this instead

**Comment by srdtrk** [comment] 2024-06-12 11:49
I'm closing this issue after discussion with @merkletreeibc since we have no way of reproducing this issue. It's not clear that this issue has actually occurred as described. However, I will be creating a new issue to allow users to switch versions on mobile

**Closed by srdtrk** 2024-06-12 11:49 UTC
Labels: docs
