### ISSUE TITLE
Push protobuf schema to buf schema registry

### ISSUE THREAD

**Issue by devashishdxt** [cosmos/ibc-go#2183] opened 2022-09-05 04:17 UTC
Push the protobuf schema to buf schema registry similar to cosmos-sdk: https://buf.build/cosmos/cosmos-sdk

**Comment by crodriguezvega** [comment] 2022-09-05 08:26
Thanks for opening this issue, @devashishdxt, but I believe this is a duplicate of #1345, right?

I will close it for now then.

**Closed by crodriguezvega** 2022-09-05 08:26 UTC
