### ISSUE TITLE
redundant txs potentially not being rejected across different blocks

### ISSUE THREAD

**Issue by charleenfei** [cosmos/ibc-go#1077] opened 2022-03-07 12:47 UTC
## Summary of Bug

as discussed in the ibc internal channel:

packet sequences 126158 and 126159 JUNO -> OSMO (both running ibc-go v2.02) were successfully relayed in block 3,415,485 https://www.mintscan.io/osmosis/txs/415017A5A66EE0BF601A07668A0975B61DA5693B3EF2F8DF876C580919E10012

however, the same packet sequences were again available to relay in block 3,415,496 and there were two failed relay attempts in this block:

https://www.mintscan.io/osmosis/txs/49635CB97E607F8B320D0B4A38000B4A8BD5120D27982901B843E395900BBB37
https://www.mintscan.io/osmosis/txs/DD01B23DE3A4268B053C20CFCC2A51252CEEAECB492BAFC7C1B0B2815927D541

wasn't the antehandler change supposed to prevent these cases of redundant relaying across two blocks?

## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by colin-axner** [comment] 2022-03-07 13:51
It'd be good if we could reproduce the issue. It's hard to debug this issue without more information since it could be an issue with the validators setup, tendermint, or our code. In theory the second transactions should have been dropped from the mempool of any node running this ante handler, but given that these transactions fail on account sequence mismatch, I'm wondering why the transactions wouldn't have been dropped on that issue? 

@AdityaSripal what happens if the block fills up with transactions. Does CheckTx get rerun on every tx in the mempool?

**Comment by AdityaSripal** [comment] 2022-03-07 18:32
Agreed that we need to understand more about the setup. Was `Recheck_Tx` enabled on these nodes. Do Osmosis and Juno include our `AnteDecorator` in their antehandler?

> what happens if the block fills up with transactions. Does CheckTx get rerun on every tx in the mempool?

CheckTx gets run against the latest committed state before a tx is first included in the mempool

And it gets rerun after each block is committed (against the new committed state), **only if** `recheck_tx` is enabled on the node

**Comment by AdityaSripal** [comment] 2022-03-07 18:37
Actually assuming that the sequence `126160` was not received in a previous block this is expected behaviour.

We explicitly allow redundant messages to be rerun if they are batched with fresh messages. This is to prevent relayers from missing out on relaying new packets because they batched it with an old packet.

And so that would explain why the first tx went through.

And the reason the second tx went through, is because even though `126160` is redundant, it only became redundant in the same block. Which we do not yet handle correctly.

**Comment by crodriguezvega** [comment] 2022-09-19 09:01
@charleenfei Have you heard or seen this behavior again? If not, then I think we can close the issue; and if we see this happening again, then we can open a new one.

**Closed** 2022-09-22 09:26 UTC
Labels: bug
